version: 2.1

parameters:
  dev-orb-version:
    type: string
    default: "dev:testing"
  run-integration-tests:
    type: boolean
    default: false

orbs:
  gor: hubci/goreleaser@<< pipeline.parameters.dev-orb-version >>
  orb-tools: circleci/orb-tools@10.1

executors:
  cimg:
    docker:
      - image: cimg/base:2024.06
  linux:
    machine:
      image: ubuntu-2204:2024.04.1
  mac:
    macos:
      xcode: 14.0.0

workflows:
  main-wf:
    when:
      not:
        or:
          - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
          - << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: hubci/goreleaser
          alpha-version-ref: "dev:testing"
          checkout: true
          attach-workspace: false
          orb-path: orb.yml
          requires:
            - orb-tools/lint
          context: circleci-ctx
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: circleci-ctx
          requires:
            - orb-tools/publish-dev
  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-install:
          matrix:
            parameters:
              runner:
                - cimg
                - linux
                - mac
      - gor/release:
          matrix:
            parameters:
              image:
                - cimg
                - linux
                - mac
              version:
                - "1.20.0"
                - "1.21.1"
              go-version:
                - "1.20.8"
                - "1.21.1"
              dry-run:
                - true
      - gor/release:
          name: config-test
          version: "1.21.1"
          go-version: "1.21.1"
          dry-run: true
          config: "./.goreleaser-mac.yml"
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: hubci/goreleaser
          add-pr-comment: true
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          requires:
            - integration-test-install
            - gor/release
            - config-test
          filters:
            branches:
              only: trunk
          context: circleci-ctx
  weekly-cron-wf:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - orb-tools/publish-dev:
          orb-name: hubci/goreleaser
          alpha-version-ref: "dev:testing"
          checkout: true
          attach-workspace: false
          orb-path: orb.yml
          requires:
            - orb-tools/lint
          context: circleci-ctx


jobs:
  integration-test-install:
    parameters:
      runner:
        type: executor
    executor: <<parameters.runner>>
    steps:
      - gor/install:
          version: "1.21.1"
      - run:
          name: "Try running GoReleaser"
          command: goreleaser --version
